# Generated by Django 4.1.2 on 2022-10-17 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redirect', '0003_urlshortner_redirect_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlshortner',
            name='redirect_to',
        ),
    ]
