# Generated by Django 4.1.2 on 2022-10-17 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redirect', '0005_urlshortner_added_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshortner',
            name='added_date',
            field=models.DateField(verbose_name=datetime.datetime(2022, 10, 17, 19, 10, 53, 668928)),
        ),
    ]
