# Generated by Django 4.1.2 on 2022-10-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redirect', '0007_alter_urlshortner_added_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlshortner',
            name='added_date',
        ),
        migrations.AddField(
            model_name='urlshortner',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
