# Generated by Django 4.1.2 on 2022-10-18 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redirect', '0008_remove_urlshortner_added_date_urlshortner_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlshortner',
            name='date',
        ),
    ]
