# Generated by Django 4.1.2 on 2022-10-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redirect', '0009_remove_urlshortner_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshortner',
            name='url',
            field=models.URLField(max_length=75),
        ),
    ]
