# Generated by Django 4.1.2 on 2022-10-24 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redirect', '0010_alter_urlshortner_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='URLshortner',
            new_name='URL_Shortner',
        ),
    ]
