# Generated by Django 4.1.2 on 2022-10-24 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redirect', '0011_rename_urlshortner_url_shortner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='URL_Shortner',
            new_name='UrlShortner',
        ),
    ]
