# Generated by Django 4.1.2 on 2022-12-17 13:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('redirect', '0012_rename_url_shortner_urlshortner'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlshortner',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created on'),
        ),
    ]
